### ISSUE TITLE
Just an appreciation, no bug

### ISSUE THREAD

**Issue by firdaus-aziz** [tadams42/flask-rest-jsonapi-next#1]
Thank you for forking and keeping this extension updated. It's so hard to find updated JSON:API extension for Flask.

**Comment by tadams42** [comment]
Well, I'm just scratching my itch here :smirk: . I have this thing deployed in a few places and I need it to be up to date. 

Thus said, it is really nice to know someone else finds it useful: you are welcome :blush:
